### ISSUE TITLE
Does not work with v4

### ISSUE THREAD

**Issue by wojtekmaj** [hongaar/semantic-release-yarn#209]
<details>
<summary>Full error stack</summary>
<pre>
Error: Command failed with exit code 1: yarn plugin import version
➤ YN0051: Couldn't find a plugin named @yarnpkg/plugin-version on the remote registry.
A plugin named @yarnpkg/plugin-version is already installed; possibly attempting to import a built-in plugin.
➤ YN0000: Failed with errors in 0s 378ms
    at makeError (file:///home/vsts/work/1/s/node_modules/execa/lib/error.js:60:11)
    at handlePromise (file:///home/vsts/work/1/s/node_modules/execa/index.js:124:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async installYarnPluginIfNeeded (file:///home/vsts/work/1/s/node_modules/semantic-release-yarn/dist/yarn-plugins.js:13:9)
    at async prepare (file:///home/vsts/work/1/s/node_modules/semantic-release-yarn/dist/prepare.js:20:5)
    at async prepare (file:///home/vsts/work/1/s/node_modules/semantic-release-yarn/dist/index.js:31:5)
    at async validator (file:///home/vsts/work/1/s/node_modules/semantic-release/lib/plugins/normalize.js:36:24)
    at async file:///home/vsts/work/1/s/node_modules/semantic-release/lib/plugins/pipeline.js:38:36
    at async Promise.all (index 0)
    at async next (file:///home/vsts/work/1/s/node_modules/p-reduce/index.js:15:44) {
  shortMessage: 'Command failed with exit code 1: yarn plugin import version',
  command: 'yarn plugin import version',
  escapedCommand: 'yarn plugin import version',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: "➤ YN0051: Couldn't find a plugin named @yarnpkg/plugin-version on the remote registry.\n" +
    'A plugin named @yarnpkg/plugin-version is already installed; possibly attempting to import a built-in plugin.\n' +
    '➤ YN0000: Failed with errors in 0s 378ms',
  stderr: '',
  cwd: '/home/vsts/work/1/s/packages/design-system',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  pluginName: 'semantic-release-yarn'
</pre>
</details>

This is the most important bit:

> A plugin named @yarnpkg/plugin-version is already installed; possibly attempting to import a built-in plugin.

This comes as a surprise, because installYarnPluginIfNeeded looks really well written and I don't see why it wouldn't work 🤔

Anyway, the simplest fix would be to just skip installYarnPluginIfNeeded altogether if v4 is detected, as all plugins are now built-in.

**Comment by hongaar** [comment]
Thanks for reporting this. This was previously addressed in https://github.com/hongaar/semantic-release-yarn/pull/147. I'll take a look to see what can be improved.

**Comment by wojtekmaj** [comment]
Wait, no, I'm an idiot, I was running 2.0.0 🤦 I did not realize fix for v4 would have been released months before v4 😂 Sorry!

**Comment by hongaar** [comment]
No worries. Thanks to [nigelzor](https://github.com/nigelzor) we were well prepared for yarn v4!
