### ISSUE TITLE
Workspaces are not correctly handled in yarn v4

### ISSUE THREAD

**Issue by ShauniArima** [hongaar/semantic-release-yarn#210]
Using `workspaces` with yarn v4 does not work as `--all`, `--recursive` or `--worktree` argument is mandatory now.

Link to the changelog of `yarn 4` : https://yarnpkg.com/advanced/changelog#major-changes

Example of stacktrace:
```
Usage Error: Invalid option schema: missing at least one property from "all", "recursive", "since", or "worktree"
$ yarn workspaces foreach [--from #0] [-A,--all] [-R,--recursive] [-W,--worktree] [-v,--verbose] [-p,--parallel] [-i,--interlaced] [-j,--jobs #0] [-t,--topological] [--topological-dev] [--include #0] [--exclude #0] [--no-private] [--since] [-n,--dry-run] <commandName> ...
    at makeError (file:///builds/Shauni/monorepo-example/.yarn/cache/execa-npm-8.0.1-0211bd404c-d2ab5fe1e2.zip/node_modules/execa/lib/error.js:60:11)
    at handlePromise (file:///builds/Shauni/monorepo-example/.yarn/cache/execa-npm-8.0.1-0211bd404c-d2ab5fe1e2.zip/node_modules/execa/index.js:124:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async prepare (file:///builds/Shauni/monorepo-example/.yarn/__virtual__/semantic-release-yarn-virtual-1341558b4b/0/cache/semantic-release-yarn-npm-2.0.2-cefdfa588d-51b71877f1.zip/node_modules/semantic-release-yarn/dist/prepare.js:28:5)
    at async prepare (file:///builds/Shauni/monorepo-example/.yarn/__virtual__/semantic-release-yarn-virtual-1341558b4b/0/cache/semantic-release-yarn-npm-2.0.2-cefdfa588d-51b71877f1.zip/node_modules/semantic-release-yarn/dist/index.js:31:5)
    at async validator (file:///builds/Shauni/monorepo-example/.yarn/cache/semantic-release-npm-22.0.5-ef3ebea609-c8ec10d4a6.zip/node_modules/semantic-release/lib/plugins/normalize.js:36:24)
    at async file:///builds/Shauni/monorepo-example/.yarn/cache/semantic-release-npm-22.0.5-ef3ebea609-c8ec10d4a6.zip/node_modules/semantic-release/lib/plugins/pipeline.js:38:36
    at async Promise.all (index 0)
    at async next (file:///builds/Shauni/monorepo-example/.yarn/cache/p-reduce-npm-3.0.0-a4e7df18a7-387de355e9.zip/node_modules/p-reduce/index.js:15:44) {
  shortMessage: 'Command failed with exit code 1: yarn workspaces foreach --topological --verbose --no-private version 1.1.0 --immediate',
  command: 'yarn workspaces foreach --topological --verbose --no-private version 1.1.0 --immediate',
  escapedCommand: 'yarn workspaces foreach --topological --verbose --no-private version 1.1.0 --immediate',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '\x1B[31m\x1B[1mUsage Error\x1B[22m\x1B[39m: Invalid option schema: missing at least one property from "all", "recursive", "since", or "worktree"\n' +
    '\n' +
    '\x1B[1m$ \x1B[22myarn workspaces foreach [--from #0] [-A,--all] [-R,--recursive] [-W,--worktree] [-v,--verbose] [-p,--parallel] [-i,--interlaced] [-j,--jobs #0] [-t,--topological] [--topological-dev] [--include #0] [--exclude #0] [--no-private] [--since] [-n,--dry-run] <commandName> ...',
  stderr: '',
  cwd: '/builds/Shauni/monorepo-example',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  pluginName: 'semantic-release-yarn'
}
```

I will suggest to use `--worktree` as it was the default value in v3 ^^

Edit: after some tests it seems that `--worktree` doesn't exist in v3. Should we use `--all` or another argument to avoid checking yarn's version?

**Comment by hongaar** [comment]
Thanks for reporting this [ShauniArima](https://github.com/ShauniArima), this should now be fixed with the above release :arrow_up:

**Comment by ShauniArima** [comment]
Thank you! 🙂
